app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class Quote():
    def __init__(self, author, text):
        self.author=author
        self.text=text


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    

class User(UserMixin, db.Model):
    __tablename__='users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    about = db.Column(db.String(255))
    avatar = db.Column(db.String())
    password_encrypt=db.Column(db.String(128))
    post = db.relationship('Post', backref='user', lazy='dynamic')
    comments = db.relationship('Comments', backref='comments', lazy='dynamic')

    @property   #write-only
    def password(self):
        raise AttributeError('You can not read this attribute')

    @password.setter
    def password(self, password):
        self.password_encrypt = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_encrypt, password)

    def __repr__(self):
        return f'User{self.username}'


class Post(db.Model):
    __tablename__='posts'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    comments = db.relationship('Comments', backref='post', lazy='dynamic')
    
    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Post{self.text}'


class Comments(db.Model):
    __tablename__='comments'
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    comment = db.Column(db.String(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,post_id):
        comments = Comments.query.filter_by(post_id=post_id)
        return comments
    
    def __repr__(self):
        return f'Comments:{self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField ,SubmitField
from wtforms.validators import input_required


class EditProfile(FlaskForm):
    about = TextAreaField('Tell us about yourself.',validators = [input_required()])
    submit = SubmitField('Update')


class UpdatePost(FlaskForm):
    text = TextAreaField('Edit post here',validators = [input_required()])
    submit = SubmitField('Update')


class PostForm(FlaskForm):
    post_text = TextAreaField('New Post', validators=[input_required()]) 
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    post_comment = TextAreaField('Make a comment', validators=[input_required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import ProductionConfig, config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail




bootstrap = Bootstrap()
db=SQLAlchemy()
login_manager=LoginManager()
mail = Mail()
photos = UploadSet('photos',IMAGES)
login_manager.session_protection='string'
login_manager.login_view='auth.login'

def create_app(config_name=ProductionConfig):
    app = Flask(__name__)

    #set up
    app.config.from_object(ProductionConfig)

    #init
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    #reg blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    
    configure_uploads(app,photos)
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, error

app/main/views.py
import os
from . import main
from flask import render_template, request, redirect, url_for, abort
from ..models import User, Post, Comments
from flask_login import login_required, current_user
from .forms import EditProfile, PostForm, CommentForm, UpdatePost
from .. import db, photos
from ..requests import get_quote
from sqlalchemy import desc
from ..email import mail_message


@main.route('/')
def home():
    quote = get_quote()

    post=Post.query.all()
    identification = Post.user_id
    posted_by = User.query.filter_by(id=identification).first()
    user = User.query.filter_by(id=current_user.get_id()).first()

    recent_post = Post.query.order_by(desc(Post.id)).all()

    return render_template('post.html', quote=quote, posts=post, posted_by=posted_by, user=user, recent_post=recent_post)


@main.route('/new_post', methods=['GET','POST'])
@login_required
def post_form():
    post_form = PostForm()
    if post_form.validate_on_submit():
        text = post_form.post_text.data
        new_post = Post(text=text, user=current_user)
        new_post.save_post()

        data = User.query.all()
        for user in data:
            mail_message('New post up!', 'email/new_post', user.email, user=user)
            return redirect(url_for('main.home'))
    return render_template('new_post.html', post_form=post_form, )


@main.route('/edit_post/<int:post_id>', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    form = UpdatePost()
    if form.validate_on_submit():
        post.text=form.text.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.home', post_id=post.id))
    return render_template('edit_post.html', form=form)


@main.route('/delete_post/<int:post_id>', methods=['GET','POST'])
@login_required
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first()

    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('.home', post_id=post.id))


@main.route('/comments/<int:post_id>', methods=['GET','POST'])
def post_comments(post_id):
    comments = Comments.get_comments(post_id)

    post = Post.query.get(post_id)
    post_posted_by = post.user_id
    user = User.query.filter_by(id=post_posted_by).first()

    form = CommentForm()
    if form.validate_on_submit():
        comment = form.post_comment.data      
        new_comment = Comments(comment=comment, post_id=post_id, user_id=current_user.get_id())
        new_comment.save_comment()
        return redirect(url_for('main.post_comments',post_id = post_id))

    return render_template('comments.html', comment_form=form, comments=comments, post = post, user=user)


@main.route('/delete_comment/<int:comment_id>', methods=['GET','POST'])
@login_required
def delete_comment(comment_id):
    comment = Comments.query.filter_by(id=comment_id).first()

    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('.home', comment_id=comment.id))



@main.route('/user/<name>', methods=['GET','POST'])
@login_required
def profile(name):
    user = User.query.filter_by(username=name).first()
    if user is None:
        abort(404)

    form=EditProfile()
    if form.validate_on_submit():
        user.about=form.about.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile', name=user.username))
    return render_template('profile/profile.html', user=user, form=form)


@main.route('/user/<name>/edit/pic', methods=['POST'])
@login_required
def update_pic(name):
    user=User.query.filter_by(username=name).first()
    if 'photo' in request.files:
        filename=photos.save(request.files['photo'])
        path=f'photos/{filename}'
        user.avatar=path
        db.session.commit()
    return redirect(url_for('main.profile', name=name))

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- add style and title tag -->
    {% block head %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title> {% block title %} {% endblock %} POST </title>
    {% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">GEENAH'S POSTS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">

                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/new_post" class="text-white">Add a Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{{url_for('main.profile',name=current_user.username)}}">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>{{current_user.username}}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{{url_for('auth.logout')}}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{{url_for('auth.login')}}">Sign In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %} {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

app/templates/categories.html
{% extends 'base.html' %}
<!-- content -->
{% block content %}
<div class="container">
    {% if post %} {%for item in post %}
    <h4 class="card-title">Category: {{item.category}} </h4>
    <div class=" card horizontal p-2">
        <div class="card-stacked">
            <div class="card-content">
                <p class="text-right text-capitalize">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    </svg> {{posted_by.username}} </p>
                <p> {{ item.text}} </p>
                <ul class="list-inline d-flex justify-content-between">
                    <li class="list-inline-item">
                        <span> 
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-square-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h2.5a2 2 0 0 1 1.6.8L8 14.333 9.9 11.8a2 2 0 0 1 1.6-.8H14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                <path fill-rule="evenodd" d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                            </svg>
                            <a href="/comments/{{item.id}}" class="text-dark">Comments</a> 
                        </span>
                    </li>
                    <li class="list-inline-item">
                        <button>
                            <a href="/voting" class="text-dark">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                            </svg>
                            </a> 
                        </button>
                        <button>
                            <a href="/voting" class="text-dark">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                                </svg>
                            </a>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor %} {% endif %}
</div>
{% endblock %}

app/templates/comments.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf%}

<!-- head -->
{% block title %} POST | Comments {% endblock %}


<!-- content -->
{% block content %}
<div class="container">
    <div class="row mb-5">
        <div class=" card horizontal p-2">
            <div class="card-stacked">
                <div class="card-content">
                    <p class="text-right text-capitalize">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    </svg> {{user.username}} </p>
                    <p> {{ post.text}} </p>

                </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="row">
        <!-- comments -->
        <div class="col-md-2"></div>

        <div class="col-md-8">
            {{wtf.quick_form(comment_form)}}
            <br>
            <h3 class="font-italic"> <u>COMMENTS</u> </h3>
            {% if comments %} {% for item in comments %}
            <div class="box">
                <p class="pr-2 pl-2">{{item.comment}}</p>
                <p class="text-right">
                    <a href="/delete_comment/{{item.id}}" class="text-dark">
                        <svg width="1.2em" height="1.2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                </p>
            </div>
            <br> {% endfor %} {% endif %}
        </div>

        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/edit_post.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf%}

<!-- head -->
{% block title %} PITCH | new {% endblock %}


<!-- content -->
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf%}

<!-- head -->
{% block title %} PITCH | new {% endblock %}


<!-- content -->
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(pitch_form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf%}

<!-- head -->
{% block title %} PITCH | new {% endblock %}


<!-- content -->
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(post_form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/not_found.html
{% extends 'base.html' %}

<!-- gif -->
{% block title %} POST | Error {% endblock %}

<!-- style -->
{% block head%} {{ super() }}
<style>
    body {
        background: url('/static/img/not_foundd.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center center;
        background-attachment: fixed;
    }
</style>
{% endblock %}

<!-- text -->
{% block content %}
<h3 class="text-center alert-warning"> We cant find your search please</h3>
<p class="text-center text-danger"> Check the url and try again</p>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %}

<!-- head -->
{% block title %} PITCH | Profile {% endblock %}


<!-- content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            {% if user.avatar %}
            <img src="{{url_for('static',filename=user.avatar)}}" alt="" class="img-thumbnail"> {%else%}
            <p>No profile picture</p>
            {% endif %}

            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.about %}
            <p> {{user.about}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>
        <div class="offset-1 col-md-6">
            <h3>Update my profile</h3>
            <!-- form -->
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
            <br> {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{% endblock %}